### ISSUE TITLE
Incomplete payload crashes validator

### ISSUE THREAD

**Issue by bgschiller** [gcanti/io-ts#358]
### Current Behavior

Under io-ts version 2.0.1, the following code crashes with a TypeError:

```
> const t = require('io-ts')
> LoginParams = t.type({ username: t.string, password: t.string })
> LoginParams.decode({ username: 'brian' })
TypeError: Cannot read property 'length' of undefined
    at pushAll (/Users/brian/code/improving-on-express/livecode/node_modules/io-ts/lib/index.js:120:16)
    at /Users/brian/code/improving-on-express/livecode/node_modules/io-ts/lib/index.js:529:21
    at Right.chain (/Users/brian/code/improving-on-express/livecode/node_modules/fp-ts/lib/Either.js:208:16)
    at chain (/Users/brian/code/improving-on-express/livecode/node_modules/fp-ts/lib/Either.js:627:41)
    at InterfaceType.validate (/Users/brian/code/improving-on-express/livecode/node_modules/io-ts/lib/index.js:514:16)
    at InterfaceType.Type.decode (/Users/brian/code/improving-on-express/livecode/node_modules/io-ts/lib/index.js:74:21)
```

### Expected behavior

With a previous version, 1.8.6, this worked without error.

```
> const t = require('io-ts')
> LoginParams = t.type({ username: t.string, password: t.string })
> LoginParams.decode({ username: 'brian' })
left([{
 ...
}])
```
### Reproducible example

```javascript
const t = require('io-ts');
const LoginParams = t.type({ username: t.string, password: t.string });
LoginParams.decode({ username: 'brian' });
```

### Suggested solution(s)

This seems like a regression, but perhaps I'm just using it wrong?

### Your environment

Which versions of io-ts are affected by this issue? Did this work in previous versions of io-ts?

| Software   | Version(s) |
| ---------- | ---------- |
| io-ts      |       2.0.1     |
| fp-ts      |       1.19.5     |
| TypeScript |       3.5.3  |

**Comment by DenisFrezzato** [comment]
As specified by `peerDependencies`, `io-ts@2` needs `fp-ts@^2` to work properly.

**Comment by bgschiller** [comment]
Ah, thank you. That was definitely the problem.
