### ISSUE TITLE
Validating input throws a TypeError if fp-ts is not installed

### ISSUE THREAD

**Issue by sbleon** [gcanti/io-ts#473]
### Current Behavior

When I fail to follow the installation instructions, and don't install `fp-ts`, `io-ts` seems to work until I try to `decode` invalid input. When I do that, this error is thrown:

```
TypeError: Cannot read property 'length' of undefined
    at pushAll (/Users/leon/code/csubs/backend_node/node_modules/io-ts/lib/index.js:131:16)
    at /Users/leon/code/csubs/backend_node/node_modules/io-ts/lib/index.js:602:21
    at Right.chain (/Users/leon/code/csubs/node_modules/fp-ts/lib/Either.js:208:16)
    at chain (/Users/leon/code/csubs/node_modules/fp-ts/lib/Either.js:627:41)
    at InterfaceType.validate (/Users/leon/code/csubs/backend_node/node_modules/io-ts/lib/index.js:593:16)
    at InterfaceType.Type.decode (/Users/leon/code/csubs/backend_node/node_modules/io-ts/lib/index.js:85:21)
    at Object.<anonymous> (/Users/leon/code/csubs/backend_node/src/scripts/test-io-ts.js:9:11)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
```

### Expected behavior

If `fp-ts` is not installed, it would be great if I got a message saying "It looks like you forgot to install `fp-ts`. Please review the installation instructions."

### Reproducible example

```
import * as t  from 'io-ts';

const iface = t.type({id: t.number});

try {
  iface.decode({id: 'foo'});
  console.log('No error');
} catch (e) {
  console.error('Caught Error');
  console.error(e);
}
```

### Suggested solution(s)

Sorry, I'm not exactly sure how to go about detecting a missing node package.

### Additional context

I'm a noob with Typescript and `io-ts` and I'm bad at reading instructions.

### Your environment

Which versions of io-ts are affected by this issue? Did this work in previous versions of io-ts?

| Software   | Version(s) |
| ---------- | ---------- |
| io-ts      |    2.2.3        |
| fp-ts      |  not installed          |
| TypeScript |  3.9.2          |

**Comment by volkanunsal** [comment]
Your project is not configured right. You have 2 `node_modules` directories. Your `fp-ts` is installed in `/Users/leon/code/csubs/node_modules` whereas your `io-ts` is installed in `/Users/leon/code/csubs/backend_node/node_modules`. If you remove the top level folder, and try again, you should get a notification about missing peerDependencies. Install `fp-ts` in the same project and it should work right.

**Comment by sbleon** [comment]
Awesome. Thanks, Volkan! I had a feeling I was doing something wrong.
